// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVPUq5LapilP3gPPHb1pPSn_1MXyfpd88',
    appId: '1:237156276453:web:ba98b429bf16feb4cbdc0c',
    messagingSenderId: '237156276453',
    projectId: 'farmer-ce337',
    authDomain: 'farmer-ce337.firebaseapp.com',
    storageBucket: 'farmer-ce337.firebasestorage.app',
    measurementId: 'G-VXPT63E41S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJiMzBhFLGZ2Tk7wBQFAuI5EecX56fTrY',
    appId: '1:237156276453:android:53ab3b0e3b75d9b7cbdc0c',
    messagingSenderId: '237156276453',
    projectId: 'farmer-ce337',
    storageBucket: 'farmer-ce337.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAorSFyXyeL9bY-ipsqvL8Kv5kNMN2pKPI',
    appId: '1:237156276453:ios:64a9c53d89a55c3acbdc0c',
    messagingSenderId: '237156276453',
    projectId: 'farmer-ce337',
    storageBucket: 'farmer-ce337.firebasestorage.app',
    iosBundleId: 'com.example.farmer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAorSFyXyeL9bY-ipsqvL8Kv5kNMN2pKPI',
    appId: '1:237156276453:ios:64a9c53d89a55c3acbdc0c',
    messagingSenderId: '237156276453',
    projectId: 'farmer-ce337',
    storageBucket: 'farmer-ce337.firebasestorage.app',
    iosBundleId: 'com.example.farmer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVPUq5LapilP3gPPHb1pPSn_1MXyfpd88',
    appId: '1:237156276453:web:99ac4ecffd21619acbdc0c',
    messagingSenderId: '237156276453',
    projectId: 'farmer-ce337',
    authDomain: 'farmer-ce337.firebaseapp.com',
    storageBucket: 'farmer-ce337.firebasestorage.app',
    measurementId: 'G-Y0P88HW1SN',
  );
}
